// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqevjduzyvmtumnvjsic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxZXZqZHV6eXZtdHVtbnZqc2ljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMTIwNzAsImV4cCI6MjA2MDg4ODA3MH0.x45h9QM0YDNG2QuesI2crDNDDMbqAkkPfJOzX4W98MI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);